<?php

return [
    'catalog_version' => '2026-06-06',

    'areas' => [
        [
            'key' => 'billing',
            'label' => 'Facturacao',
            'permissions' => [
                'manage-sales-invoices',
                'manage-any-sales-invoices',
                'manage-own-sales-invoices',
                'view-sales-invoices',
                'create-sales-invoices',
                'edit-sales-invoices',
                'delete-sales-invoices',
                'post-sales-invoices',
                'print-sales-invoices',
                'manage-sales-return-invoices',
                'manage-any-sales-return-invoices',
                'manage-own-sales-return-invoices',
                'view-sales-return-invoices',
                'create-sales-return-invoices',
                'delete-sales-return-invoices',
                'approve-sales-returns-invoices',
                'complete-sales-returns-invoices',
                'manage-sales-proposals',
                'manage-any-sales-proposals',
                'manage-own-sales-proposals',
                'view-sales-proposals',
                'create-sales-proposals',
                'edit-sales-proposals',
                'delete-sales-proposals',
                'print-sales-proposals',
                'sent-sales-proposals',
                'accept-sales-proposals',
                'convert-sales-proposals',
                'reject-sales-proposals',
                'manage-purchase-invoices',
                'manage-any-purchase-invoices',
                'manage-own-purchase-invoices',
                'view-purchase-invoices',
                'create-purchase-invoices',
                'edit-purchase-invoices',
                'delete-purchase-invoices',
                'post-purchase-invoices',
                'print-purchase-invoices',
                'manage-purchase-return-invoices',
                'manage-any-purchase-return-invoices',
                'manage-own-purchase-return-invoices',
                'view-purchase-return-invoices',
                'create-purchase-return-invoices',
                'delete-purchase-return-invoices',
                'approve-purchase-returns-invoices',
                'complete-purchase-returns-invoices',
            ],
        ],
        [
            'key' => 'accounting',
            'label' => 'Contabilidade',
            'permissions' => [
                'manage-account',
                'manage-account-dashboard',
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'manage-chart-of-accounts',
                'manage-any-chart-of-accounts',
                'manage-own-chart-of-accounts',
                'view-chart-of-accounts',
                'create-chart-of-accounts',
                'edit-chart-of-accounts',
                'delete-chart-of-accounts',
                'manage-double-entry',
                'manage-balance-sheets',
                'view-balance-sheets',
                'create-balance-sheets',
                'finalize-balance-sheets',
                'delete-balance-sheets',
                'print-balance-sheets',
                'year-end-close',
                'manage-trial-balance',
                'print-trial-balance',
                'manage-double-entry-reports',
                'view-general-ledger',
                'view-account-statement',
                'view-journal-entry',
                'view-account-balance',
                'view-cash-flow',
                'view-expense-report',
            ],
        ],
        [
            'key' => 'treasury',
            'label' => 'Tesouraria',
            'permissions' => [
                'manage-bank-accounts',
                'manage-any-bank-accounts',
                'manage-own-bank-accounts',
                'view-bank-accounts',
                'create-bank-accounts',
                'edit-bank-accounts',
                'delete-bank-accounts',
                'manage-bank-transactions',
                'reconcile-bank-transactions',
                'manage-bank-transfers',
                'manage-any-bank-transfers',
                'manage-own-bank-transfers',
                'view-bank-transfers',
                'create-bank-transfers',
                'edit-bank-transfers',
                'delete-bank-transfers',
                'process-bank-transfers',
                'manage-customer-payments',
                'manage-any-customer-payments',
                'manage-own-customer-payments',
                'view-customer-payments',
                'create-customer-payments',
                'create-high-value-customer-payments',
                'create-foreign-currency-customer-payments',
                'use-all-bank-accounts-for-customer-payments',
                'approve-customer-payments',
                'cleared-customer-payments',
                'delete-customer-payments',
                'manage-vendor-payments',
                'manage-any-vendor-payments',
                'manage-own-vendor-payments',
                'view-vendor-payments',
                'create-vendor-payments',
                'create-high-value-vendor-payments',
                'create-foreign-currency-vendor-payments',
                'use-all-bank-accounts-for-vendor-payments',
                'approve-vendor-payments',
                'cleared-vendor-payments',
                'delete-vendor-payments',
            ],
        ],
        [
            'key' => 'hr',
            'label' => 'Recursos Humanos',
            'permissions' => [
                'manage-hrm',
                'manage-hrm-dashboard',
                'manage-employees',
                'manage-any-employees',
                'manage-own-employees',
                'view-employees',
                'view-sensitive-employee-data',
                'create-employees',
                'edit-employees',
                'delete-employees',
                'manage-attendances',
                'manage-any-attendances',
                'manage-own-attendances',
                'view-attendances',
                'create-attendances',
                'edit-attendances',
                'delete-attendances',
                'clock-in',
                'clock-out',
                'manage-leave-applications',
                'manage-any-leave-applications',
                'manage-own-leave-applications',
                'manage-leave-status',
                'view-leave-applications',
                'create-leave-applications',
                'edit-leave-applications',
                'delete-leave-applications',
                'manage-payrolls',
                'manage-any-payrolls',
                'manage-own-payrolls',
                'view-payrolls',
                'view-any-payrolls',
                'view-own-payrolls',
                'run-payrolls',
            ],
        ],
        [
            'key' => 'system',
            'label' => 'Sistema',
            'permissions' => [
                'manage-users',
                'manage-any-users',
                'manage-own-users',
                'create-users',
                'edit-users',
                'delete-users',
                'change-password-users',
                'toggle-status-users',
                'impersonate-users',
                'view-login-history',
                'manage-roles',
                'view-roles',
                'create-roles',
                'edit-roles',
                'delete-roles',
                'manage-settings',
                'edit-settings',
                'manage-system-settings',
                'edit-system-settings',
                'manage-email-settings',
                'edit-email-settings',
                'manage-media',
                'manage-own-media',
                'create-media',
                'download-media',
                'delete-media',
                'manage-messenger',
                'send-messages',
                'view-messages',
            ],
        ],
    ],

    'role_templates' => [
        [
            'name' => 'finance-administrator',
            'label' => 'Administrador Financeiro',
            'permissions' => [
                'manage-account',
                'manage-account-dashboard',
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'manage-bank-accounts',
                'manage-any-bank-accounts',
                'view-bank-accounts',
                'create-bank-accounts',
                'edit-bank-accounts',
                'manage-vendor-payments',
                'manage-any-vendor-payments',
                'view-vendor-payments',
                'create-vendor-payments',
                'create-high-value-vendor-payments',
                'create-foreign-currency-vendor-payments',
                'use-all-bank-accounts-for-vendor-payments',
                'approve-vendor-payments',
                'cleared-vendor-payments',
                'manage-customer-payments',
                'manage-any-customer-payments',
                'view-customer-payments',
                'create-customer-payments',
                'create-high-value-customer-payments',
                'create-foreign-currency-customer-payments',
                'use-all-bank-accounts-for-customer-payments',
                'approve-customer-payments',
                'cleared-customer-payments',
                'manage-bank-transactions',
                'reconcile-bank-transactions',
            ],
        ],
        [
            'name' => 'finance-billing',
            'label' => 'Faturacao',
            'permissions' => [
                'manage-account-dashboard',
                'view-customers',
                'create-customers',
                'edit-customers',
                'manage-customer-payments',
                'manage-own-customer-payments',
                'view-customer-payments',
                'create-customer-payments',
                'create-foreign-currency-customer-payments',
                'manage-account-reports',
                'view-customer-balance',
                'view-customer-detail-report',
                'view-invoice-aging',
            ],
        ],
        [
            'name' => 'finance-treasury',
            'label' => 'Tesouraria',
            'permissions' => [
                'manage-account-dashboard',
                'manage-bank-accounts',
                'manage-own-bank-accounts',
                'view-bank-accounts',
                'create-bank-accounts',
                'edit-bank-accounts',
                'manage-vendor-payments',
                'manage-own-vendor-payments',
                'view-vendor-payments',
                'create-vendor-payments',
                'create-foreign-currency-vendor-payments',
                'manage-customer-payments',
                'manage-own-customer-payments',
                'view-customer-payments',
                'create-customer-payments',
                'create-foreign-currency-customer-payments',
                'manage-bank-transactions',
                'reconcile-bank-transactions',
            ],
        ],
        [
            'name' => 'finance-accountant',
            'label' => 'Contabilista',
            'permissions' => [
                'manage-account',
                'manage-account-dashboard',
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'manage-vendor-payments',
                'view-vendor-payments',
                'manage-customer-payments',
                'view-customer-payments',
                'manage-bank-transactions',
                'reconcile-bank-transactions',
            ],
        ],
        [
            'name' => 'finance-tax-specialist',
            'label' => 'Fiscalista',
            'permissions' => [
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'view-vendor-payments',
                'view-customer-payments',
                'view-customer-detail-report',
                'view-vendor-detail-report',
            ],
        ],
        [
            'name' => 'finance-auditor',
            'label' => 'Auditor Financeiro',
            'permissions' => [
                'manage-account-dashboard',
                'manage-account-reports',
                'view-bank-accounts',
                'view-vendor-payments',
                'view-customer-payments',
                'view-tax-summary',
                'view-invoice-aging',
                'view-bill-aging',
                'view-customer-detail-report',
                'view-vendor-detail-report',
            ],
        ],
        [
            'name' => 'finance-manager',
            'label' => 'Gestor Financeiro',
            'permissions' => [
                'manage-account',
                'manage-account-dashboard',
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'manage-vendor-payments',
                'manage-customer-payments',
                'approve-vendor-payments',
                'approve-customer-payments',
                'create-high-value-vendor-payments',
                'create-high-value-customer-payments',
                'manage-bank-transactions',
            ],
        ],
        [
            'name' => 'finance-payment-approver',
            'label' => 'Aprovador de Pagamentos',
            'permissions' => [
                'manage-vendor-payments',
                'manage-own-vendor-payments',
                'view-vendor-payments',
                'approve-vendor-payments',
                'cleared-vendor-payments',
                'manage-customer-payments',
                'manage-own-customer-payments',
                'view-customer-payments',
                'approve-customer-payments',
                'cleared-customer-payments',
                'create-high-value-vendor-payments',
                'create-high-value-customer-payments',
            ],
        ],
        [
            'name' => 'finance-cash-operator',
            'label' => 'Operador de Caixa',
            'permissions' => [
                'manage-account-dashboard',
                'manage-bank-accounts',
                'manage-own-bank-accounts',
                'view-bank-accounts',
                'manage-vendor-payments',
                'manage-own-vendor-payments',
                'view-vendor-payments',
                'create-vendor-payments',
                'manage-customer-payments',
                'manage-own-customer-payments',
                'view-customer-payments',
                'create-customer-payments',
                'manage-bank-transactions',
            ],
        ],
        [
            'name' => 'finance-compliance-supervisor',
            'label' => 'Supervisor de Compliance',
            'permissions' => [
                'manage-account-dashboard',
                'manage-account-reports',
                'view-tax-summary',
                'print-tax-summary',
                'view-vendor-payments',
                'view-customer-payments',
                'approve-vendor-payments',
                'approve-customer-payments',
                'create-high-value-vendor-payments',
                'create-high-value-customer-payments',
                'create-foreign-currency-vendor-payments',
                'create-foreign-currency-customer-payments',
                'view-vendor-detail-report',
                'view-customer-detail-report',
            ],
        ],
    ],
];
