<?php

return [
    'catalog_version' => '2026-06-06',

    'dimensions' => [
        [
            'key' => 'users',
            'label' => 'Utilizadores activos',
            'unit' => 'users',
            'source' => 'plan_field',
            'field' => 'number_of_users',
            'enforcement' => 'runtime',
            'description' => 'Licenças activas de utilizador atribuídas ao plano.',
        ],
        [
            'key' => 'storage_kb',
            'label' => 'Armazenamento',
            'unit' => 'KB',
            'source' => 'plan_field',
            'field' => 'storage_limit',
            'enforcement' => 'runtime',
            'description' => 'Quota de armazenamento do plano, usada por media e anexos.',
        ],
        [
            'key' => 'companies',
            'label' => 'Empresas',
            'unit' => 'company',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Entidades legais ou tenants cobertos pela subscrição.',
        ],
        [
            'key' => 'document_series',
            'label' => 'Séries documentais',
            'unit' => 'series',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Séries documentais disponíveis para faturação e contabilidade.',
        ],
        [
            'key' => 'branches',
            'label' => 'Filiais',
            'unit' => 'branches',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Filiais, lojas ou delegações operacionais.',
        ],
        [
            'key' => 'warehouses',
            'label' => 'Armazéns',
            'unit' => 'warehouses',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Armazéns e localizações de stock.',
        ],
        [
            'key' => 'pos_registers',
            'label' => 'POS',
            'unit' => 'registers',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Terminais POS ou caixas ativas.',
        ],
        [
            'key' => 'employees',
            'label' => 'Colaboradores',
            'unit' => 'employees',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Registos de colaboradores no módulo de RH.',
        ],
        [
            'key' => 'documents_per_month',
            'label' => 'Documentos por mês',
            'unit' => 'documents',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Volume mensal de documentos fiscais e operacionais.',
        ],
        [
            'key' => 'bank_accounts',
            'label' => 'Contas bancárias',
            'unit' => 'accounts',
            'source' => 'contract',
            'enforcement' => 'manual',
            'description' => 'Contas bancárias e de caixa geridas pela tesouraria.',
        ],
    ],

    'plan_families' => [
        'free' => [
            'notes' => 'Plano de entrada com operação limitada.',
            'limits' => [
                'users' => 10,
                'storage_kb' => 5000000,
                'companies' => 1,
                'document_series' => 1,
                'branches' => 1,
                'warehouses' => 1,
                'pos_registers' => 1,
                'employees' => 10,
                'documents_per_month' => 100,
                'bank_accounts' => 1,
            ],
        ],
        'starter' => [
            'notes' => 'Plano intermédio para equipas pequenas.',
            'limits' => [
                'users' => 50,
                'storage_kb' => 20000000,
                'companies' => 1,
                'document_series' => 5,
                'branches' => 3,
                'warehouses' => 3,
                'pos_registers' => 2,
                'employees' => 50,
                'documents_per_month' => 1000,
                'bank_accounts' => 3,
            ],
        ],
        'professional' => [
            'notes' => 'Plano principal para operação regular.',
            'limits' => [
                'users' => 100,
                'storage_kb' => 50000000,
                'companies' => 1,
                'document_series' => 20,
                'branches' => 10,
                'warehouses' => 10,
                'pos_registers' => 5,
                'employees' => 200,
                'documents_per_month' => 5000,
                'bank_accounts' => 10,
            ],
        ],
        'enterprise' => [
            'notes' => 'Plano de maior cobertura com limites negociados.',
            'limits' => [
                'users' => -1,
                'storage_kb' => -1,
                'companies' => 1,
                'document_series' => -1,
                'branches' => -1,
                'warehouses' => -1,
                'pos_registers' => -1,
                'employees' => -1,
                'documents_per_month' => -1,
                'bank_accounts' => -1,
            ],
        ],
        'custom' => [
            'notes' => 'Plano negociado caso a caso.',
            'limits' => [
                'users' => -1,
                'storage_kb' => -1,
                'companies' => 1,
                'document_series' => -1,
                'branches' => -1,
                'warehouses' => -1,
                'pos_registers' => -1,
                'employees' => -1,
                'documents_per_month' => -1,
                'bank_accounts' => -1,
            ],
        ],
    ],
];
