<?php

return [
    'catalog_version' => '2026-06-06',

    'modules' => [
        [
            'key' => 'account',
            'label' => 'Contabilidade e Tesouraria',
            'type' => 'package',
            'package_key' => 'Account',
            'permission_module' => 'account',
            'plan_gate' => 'PlanModuleCheck:Account',
            'route_prefixes' => ['dashboard/account', 'account/*', 'sce/*'],
            'menu_groups' => ['Contabilidade', 'Tesouraria'],
            'notes' => 'Centro financeiro, fiscal e tesouraria.',
        ],
        [
            'key' => 'double_entry',
            'label' => 'Entrada Dupla',
            'type' => 'package',
            'package_key' => 'DoubleEntry',
            'permission_module' => 'double-entry',
            'plan_gate' => 'PlanModuleCheck:DoubleEntry',
            'route_prefixes' => ['double-entry/*'],
            'menu_groups' => ['Contabilidade'],
            'notes' => 'Balancete, razao, demonstracoes e relatórios contabilisticos.',
        ],
        [
            'key' => 'product_service',
            'label' => 'Produtos e Servicos',
            'type' => 'package',
            'package_key' => 'ProductService',
            'permission_module' => 'product-service',
            'plan_gate' => 'PlanModuleCheck:ProductService',
            'route_prefixes' => ['product-service/*'],
            'menu_groups' => ['Inventario'],
            'notes' => 'Artigos, categorias, impostos, unidades, stock e armazens.',
        ],
        [
            'key' => 'sales_invoices',
            'label' => 'Facturas de Venda',
            'type' => 'core',
            'permission_module' => 'sales-invoices',
            'route_prefixes' => ['sales-invoices'],
            'menu_groups' => ['Facturacao'],
            'notes' => 'Emissao, postagem e impressao de facturas de venda.',
        ],
        [
            'key' => 'purchase_invoices',
            'label' => 'Facturas de Compra',
            'type' => 'core',
            'permission_module' => 'purchase-invoices',
            'route_prefixes' => ['purchase-invoices'],
            'menu_groups' => ['Compras'],
            'notes' => 'Emissao, postagem e impressao de facturas de compra.',
        ],
        [
            'key' => 'sales_returns',
            'label' => 'Devolucoes de Venda',
            'type' => 'core',
            'permission_module' => 'sales-return-invoices',
            'route_prefixes' => ['sales-returns'],
            'menu_groups' => ['Facturacao'],
            'notes' => 'Devolucoes, aprovacao e fecho fiscal.',
        ],
        [
            'key' => 'purchase_returns',
            'label' => 'Devolucoes de Compra',
            'type' => 'core',
            'permission_module' => 'purchase-return-invoices',
            'route_prefixes' => ['purchase-returns'],
            'menu_groups' => ['Compras'],
            'notes' => 'Devolucoes, aprovacao e fecho fiscal.',
        ],
        [
            'key' => 'sales_proposals',
            'label' => 'Citacao / Propostas',
            'type' => 'core',
            'permission_module' => 'sales-proposals',
            'route_prefixes' => ['sales-proposals'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Orcamentos, propostas e conversao para factura.',
        ],
        [
            'key' => 'pos',
            'label' => 'POS',
            'type' => 'package',
            'package_key' => 'Pos',
            'permission_module' => 'pos-orders',
            'plan_gate' => 'PlanModuleCheck:Pos',
            'route_prefixes' => ['dashboard/pos', 'pos/*'],
            'menu_groups' => ['POS'],
            'notes' => 'Vendas no ponto de venda, impressao e relatorios.',
        ],
        [
            'key' => 'hrm',
            'label' => 'Recursos Humanos',
            'type' => 'package',
            'package_key' => 'Hrm',
            'permission_module' => 'hrm',
            'plan_gate' => 'PlanModuleCheck:Hrm',
            'route_prefixes' => ['dashboard/hrm', 'hrm/*'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Colaboradores, ausencias, folha, contratos e eventos.',
        ],
        [
            'key' => 'lead',
            'label' => 'CRM',
            'type' => 'package',
            'package_key' => 'Lead',
            'permission_module' => 'lead',
            'plan_gate' => 'PlanModuleCheck:Lead',
            'route_prefixes' => ['dashboard/crm', 'crm/*'],
            'menu_groups' => ['CRM'],
            'notes' => 'Leads, funis, deals, tarefas e relatorios CRM.',
        ],
        [
            'key' => 'taskly',
            'label' => 'Projectos',
            'type' => 'package',
            'package_key' => 'Taskly',
            'permission_module' => 'project',
            'plan_gate' => 'PlanModuleCheck:Taskly',
            'route_prefixes' => ['dashboard/project', 'project/*', 'project-setup/*', 'project-report/*', 'api/taskly/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Gestao de projectos, tarefas, bugs e relatatorios.',
        ],
        [
            'key' => 'budget_planner',
            'label' => 'Planeador Orcamental',
            'type' => 'package',
            'package_key' => 'BudgetPlanner',
            'permission_module' => 'budget-planner',
            'plan_gate' => 'PlanModuleCheck:BudgetPlanner',
            'route_prefixes' => ['budget-planner/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Orcamentos e previsoes.',
        ],
        [
            'key' => 'goal',
            'label' => 'Objetivos',
            'type' => 'package',
            'package_key' => 'Goal',
            'permission_module' => 'goal',
            'plan_gate' => 'PlanModuleCheck:Goal',
            'route_prefixes' => ['goal/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Metas, acompanhamento e progressos.',
        ],
        [
            'key' => 'performance',
            'label' => 'Desempenho',
            'type' => 'package',
            'package_key' => 'Performance',
            'permission_module' => 'performance',
            'plan_gate' => 'PlanModuleCheck:Performance',
            'route_prefixes' => ['performance/*'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Avaliacoes, reviews e KPIs de pessoas.',
        ],
        [
            'key' => 'recruitment',
            'label' => 'Recrutamento',
            'type' => 'package',
            'package_key' => 'Recruitment',
            'permission_module' => 'recruitment',
            'plan_gate' => 'PlanModuleCheck:Recruitment',
            'route_prefixes' => ['recruitment/*'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Vagas, candidatos e onboarding de novos colaboradores.',
        ],
        [
            'key' => 'timesheet',
            'label' => 'Ficha de Horario',
            'type' => 'package',
            'package_key' => 'Timesheet',
            'permission_module' => 'timesheet',
            'plan_gate' => 'PlanModuleCheck:Timesheet',
            'route_prefixes' => ['timesheet/*'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Registo de horas, clock in/out e project tracking.',
        ],
        [
            'key' => 'training',
            'label' => 'Formacao',
            'type' => 'package',
            'package_key' => 'Training',
            'permission_module' => 'training',
            'plan_gate' => 'PlanModuleCheck:Training',
            'route_prefixes' => ['training/*'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Cursos, feedback e progresso de formacao.',
        ],
        [
            'key' => 'contract',
            'label' => 'Contrato',
            'type' => 'package',
            'package_key' => 'Contract',
            'permission_module' => 'contract',
            'plan_gate' => 'PlanModuleCheck:Contract',
            'route_prefixes' => ['contract/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Contratos, termos e renovacoes.',
        ],
        [
            'key' => 'calendar',
            'label' => 'Calendario',
            'type' => 'package',
            'package_key' => 'Calendar',
            'permission_module' => 'calendar',
            'plan_gate' => 'PlanModuleCheck:Calendar',
            'route_prefixes' => ['calendar/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Eventos, agendas e sincronizacoes.',
        ],
        [
            'key' => 'support_ticket',
            'label' => 'Suporte',
            'type' => 'package',
            'package_key' => 'SupportTicket',
            'permission_module' => 'helpdesk',
            'plan_gate' => 'PlanModuleCheck:SupportTicket',
            'route_prefixes' => ['helpdesk/*', 'support-ticket/*'],
            'menu_groups' => ['CRM/Suporte'],
            'notes' => 'Tickets, categorias, FAQ e respostas.',
        ],
        [
            'key' => 'messenger',
            'label' => 'Mensageiro',
            'type' => 'core',
            'permission_module' => 'messenger',
            'route_prefixes' => ['messenger/*'],
            'menu_groups' => ['CRM/Suporte'],
            'notes' => 'Mensagens, conversas, favoritos e presenca.',
        ],
        [
            'key' => 'form_builder',
            'label' => 'Criador de Formularios',
            'type' => 'package',
            'package_key' => 'FormBuilder',
            'permission_module' => 'form-builder',
            'plan_gate' => 'PlanModuleCheck:FormBuilder',
            'route_prefixes' => ['form-builder/*'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Formularios, conversoes e automatizacoes.',
        ],
        [
            'key' => 'zoom_meeting',
            'label' => 'Reunioes Zoom',
            'type' => 'package',
            'package_key' => 'ZoomMeeting',
            'permission_module' => 'zoom-meeting',
            'plan_gate' => 'PlanModuleCheck:ZoomMeeting',
            'route_prefixes' => ['zoom-meeting/*'],
            'menu_groups' => ['Operacoes'],
            'notes' => 'Agendamento e sincronizacao de reunioes.',
        ],
        [
            'key' => 'users_roles',
            'label' => 'Utilizadores e Perfis',
            'type' => 'core',
            'permission_module' => 'users',
            'route_prefixes' => ['users/*', 'roles/*'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Gestao de utilizadores, perfis e permissao base.',
        ],
        [
            'key' => 'plans',
            'label' => 'Planos e Subscricao',
            'type' => 'core',
            'permission_module' => 'plans',
            'route_prefixes' => ['plans/*', 'subscriptions/*', 'orders/*', 'add-ons/*'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Planos, checkout, ordens, add-ons e trial.',
        ],
        [
            'key' => 'settings',
            'label' => 'Configuracoes',
            'type' => 'core',
            'permission_module' => 'settings',
            'route_prefixes' => ['settings/*', 'languages/*', 'email-templates/*', 'notification-templates/*'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Configuracoes globais, idioma, email e notificacoes.',
        ],
        [
            'key' => 'media_library',
            'label' => 'Biblioteca de Media',
            'type' => 'core',
            'permission_module' => 'media',
            'route_prefixes' => ['media/*', 'media-library'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Ficheiros, pastas e uploads.',
        ],
        [
            'key' => 'ai_assistant',
            'label' => 'Assistente de IA',
            'type' => 'package',
            'package_key' => 'AIAssistant',
            'permission_module' => 'ai-assistant',
            'plan_gate' => 'PlanModuleCheck:AIAssistant',
            'route_prefixes' => ['ai-assistant/*'],
            'menu_groups' => ['Sistema'],
            'notes' => 'Prompts e automacoes de IA.',
        ],
        [
            'key' => 'warehouses',
            'label' => 'Armazens',
            'type' => 'core',
            'permission_module' => 'warehouses',
            'route_prefixes' => ['warehouses/*'],
            'menu_groups' => ['Inventario'],
            'notes' => 'Localizacao fisica do stock.',
        ],
        [
            'key' => 'transfers',
            'label' => 'Transferencias',
            'type' => 'core',
            'permission_module' => 'transfers',
            'route_prefixes' => ['transfers/*'],
            'menu_groups' => ['Inventario'],
            'notes' => 'Movimentacao interna de stock entre armazens.',
        ],
    ],
];
