<?php

return [
    'catalog_version' => '2026-06-06',

    'modules' => [
        'billing' => [
            'label' => 'Facturação',
            'priority' => 1,
            'technical_modules' => ['Account', 'ProductService'],
            'required_permissions' => [
                'manage-account',
                'manage-sales-invoices',
                'create-sales-invoices',
                'post-sales-invoices',
                'manage-sales-return-invoices',
                'manage-product-service-item',
                'manage-product-service-taxes',
                'create-customers',
            ],
            'required_config_keys' => [
                'company_profile',
                'fiscal_profile',
                'document_series',
                'accounting_period',
                'tax_profile',
                'mozambique_fiscal_compliance',
                'customer_masterdata',
                'product_masterdata',
            ],
            'steps' => [
                [
                    'key' => 'billing.configure_fiscal_profile',
                    'checklist_key' => 'configure_tax',
                    'label' => 'Configurar perfil fiscal',
                    'description' => 'Registar o NUIT, regime de IVA e dados fiscais da empresa.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-account'],
                    'config_keys' => ['company_profile', 'fiscal_profile', 'tax_profile'],
                    'evidence' => 'Perfil fiscal activo e válido.',
                ],
                [
                    'key' => 'billing.configure_document_series',
                    'checklist_key' => 'configure_series',
                    'label' => 'Criar séries documentais',
                    'description' => 'Criar e validar séries para facturas, notas de crédito e documentos associados.',
                    'order' => 20,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-sales-invoices'],
                    'config_keys' => ['document_series'],
                    'evidence' => 'Séries activas e atribuídas aos documentos fiscais.',
                ],
                [
                    'key' => 'billing.open_accounting_period',
                    'checklist_key' => 'open_period',
                    'label' => 'Abrir período contabilístico',
                    'description' => 'Garantir que existe um período contabilístico activo para a data de emissão.',
                    'order' => 30,
                    'required' => true,
                    'module_refs' => ['Account', 'DoubleEntry'],
                    'permissions' => ['manage-account'],
                    'config_keys' => ['accounting_period'],
                    'evidence' => 'Período aberto para emissão fiscal e registos contabilísticos.',
                ],
                [
                    'key' => 'billing.create_customer_masterdata',
                    'checklist_key' => 'create_customer',
                    'label' => 'Criar cliente base',
                    'description' => 'Criar um cliente de teste com NUIT, contactos e condições comerciais.',
                    'order' => 40,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['create-customers', 'edit-customers', 'view-customers'],
                    'config_keys' => ['customer_masterdata'],
                    'evidence' => 'Cliente criado e visível na factura de venda.',
                ],
                [
                    'key' => 'billing.create_product_masterdata',
                    'checklist_key' => 'create_product',
                    'label' => 'Criar produto base',
                    'description' => 'Registar produto/serviço com preço, unidade, imposto e stock quando aplicável.',
                    'order' => 50,
                    'required' => true,
                    'module_refs' => ['ProductService'],
                    'permissions' => ['manage-product-service-item', 'manage-product-service-taxes'],
                    'config_keys' => ['product_masterdata'],
                    'evidence' => 'Produto activo e seleccionável no fluxo de faturação.',
                ],
                [
                    'key' => 'billing.issue_test_invoice',
                    'checklist_key' => 'issue_invoice',
                    'label' => 'Emitir factura de teste',
                    'description' => 'Emitir uma factura de validação para confirmar séries, impostos e impacto no stock.',
                    'order' => 60,
                    'required' => false,
                    'module_refs' => ['Account', 'ProductService'],
                    'permissions' => ['create-sales-invoices', 'post-sales-invoices'],
                    'config_keys' => ['document_series', 'accounting_period', 'tax_profile'],
                    'evidence' => 'Factura gerada em estado válido e pronta para envio/arquivo.',
                ],
            ],
        ],
        'accounting' => [
            'label' => 'Contabilidade',
            'priority' => 2,
            'technical_modules' => ['Account', 'DoubleEntry'],
            'required_permissions' => [
                'manage-account',
                'manage-chart-of-accounts',
                'manage-double-entry',
                'manage-trial-balance',
                'manage-balance-sheets',
                'view-general-ledger',
            ],
            'required_config_keys' => [
                'accounting_period',
                'chart_of_accounts',
                'opening_balances',
                'closing_rules',
                'mozambique_fiscal_compliance',
                'tax_profile',
            ],
            'steps' => [
                [
                    'key' => 'accounting.configure_chart_of_accounts',
                    'checklist_key' => 'chart_of_accounts',
                    'label' => 'Configurar plano de contas',
                    'description' => 'Criar ou rever o plano de contas base da empresa.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['Account', 'DoubleEntry'],
                    'permissions' => ['manage-chart-of-accounts'],
                    'config_keys' => ['chart_of_accounts'],
                    'evidence' => 'Plano de contas visível e activo.',
                ],
                [
                    'key' => 'accounting.record_opening_balances',
                    'checklist_key' => 'opening_balances',
                    'label' => 'Registar saldos de abertura',
                    'description' => 'Introduzir saldos iniciais e validar saldos por conta.',
                    'order' => 20,
                    'required' => true,
                    'module_refs' => ['DoubleEntry'],
                    'permissions' => ['manage-double-entry'],
                    'config_keys' => ['opening_balances'],
                    'evidence' => 'Saldos de abertura carregados sem diferenças.',
                ],
                [
                    'key' => 'accounting.open_period',
                    'checklist_key' => 'period_open',
                    'label' => 'Abrir período contabilístico',
                    'description' => 'Validar que o período contabilístico está pronto para lançamentos.',
                    'order' => 30,
                    'required' => true,
                    'module_refs' => ['Account', 'DoubleEntry'],
                    'permissions' => ['manage-account'],
                    'config_keys' => ['accounting_period'],
                    'evidence' => 'Período contabilístico disponível para registo.',
                ],
                [
                    'key' => 'accounting.configure_journal_templates',
                    'checklist_key' => 'journal_templates',
                    'label' => 'Configurar diários e templates',
                    'description' => 'Definir templates de lançamentos e diários usados pela operação.',
                    'order' => 40,
                    'required' => true,
                    'module_refs' => ['DoubleEntry'],
                    'permissions' => ['manage-double-entry'],
                    'config_keys' => ['closing_rules'],
                    'evidence' => 'Diários e templates disponíveis para lançamentos automáticos.',
                ],
                [
                    'key' => 'accounting.review_trial_balance',
                    'checklist_key' => 'trial_balance_review',
                    'label' => 'Rever balancete',
                    'description' => 'Executar revisão do balancete para validar equilíbrio inicial.',
                    'order' => 50,
                    'required' => true,
                    'module_refs' => ['DoubleEntry'],
                    'permissions' => ['manage-trial-balance', 'view-general-ledger'],
                    'config_keys' => ['opening_balances'],
                    'evidence' => 'Balancete revisto e sem erros estruturais.',
                ],
                [
                    'key' => 'accounting.validate_month_end_close',
                    'checklist_key' => 'month_end_close_rehearsal',
                    'label' => 'Simular fecho mensal',
                    'description' => 'Executar uma simulação de fecho para validar regras e bloqueios.',
                    'order' => 60,
                    'required' => true,
                    'module_refs' => ['DoubleEntry'],
                    'permissions' => ['manage-double-entry', 'manage-balance-sheets'],
                    'config_keys' => ['closing_rules'],
                    'evidence' => 'Checklist de fecho mensal concluída em ambiente de validação.',
                ],
            ],
        ],
        'hr' => [
            'label' => 'Recursos Humanos',
            'priority' => 3,
            'technical_modules' => ['Hrm'],
            'required_permissions' => [
                'manage-hrm',
                'manage-employees',
                'manage-attendances',
                'manage-payrolls',
                'manage-leave-applications',
            ],
            'required_config_keys' => [
                'hr_company_profile',
                'employee_masterdata',
                'contract_templates',
                'payroll_calendar',
                'payroll_contributions',
                'leave_policy',
            ],
            'steps' => [
                [
                    'key' => 'hr.create_employee_masterdata',
                    'checklist_key' => 'employee_masterdata',
                    'label' => 'Criar colaborador',
                    'description' => 'Registar pelo menos um colaborador com dados completos e vínculo organizacional.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-employees', 'create-employees'],
                    'config_keys' => ['employee_masterdata'],
                    'evidence' => 'Colaborador activo e elegível para processos de RH.',
                ],
                [
                    'key' => 'hr.configure_contract_templates',
                    'checklist_key' => 'contract_defaults',
                    'label' => 'Configurar contratos',
                    'description' => 'Preparar modelos de contrato e regras base para admissões.',
                    'order' => 20,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-hrm'],
                    'config_keys' => ['contract_templates'],
                    'evidence' => 'Modelo de contrato disponível para novas admissões.',
                ],
                [
                    'key' => 'hr.configure_attendance_policy',
                    'checklist_key' => 'attendance_policy',
                    'label' => 'Configurar assiduidade',
                    'description' => 'Definir política de assiduidade, marcação e regras operacionais.',
                    'order' => 30,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-attendances'],
                    'config_keys' => ['hr_company_profile'],
                    'evidence' => 'Regras de assiduidade activas para a empresa.',
                ],
                [
                    'key' => 'hr.configure_leave_policy',
                    'checklist_key' => 'leave_policy',
                    'label' => 'Configurar ausências',
                    'description' => 'Definir políticas de férias, faltas e aprovações.',
                    'order' => 40,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-leave-applications'],
                    'config_keys' => ['leave_policy'],
                    'evidence' => 'Política de ausências activa e aprovável.',
                ],
                [
                    'key' => 'hr.configure_payroll_calendar',
                    'checklist_key' => 'payroll_calendar',
                    'label' => 'Configurar calendário de payroll',
                    'description' => 'Preparar o calendário salarial e as datas de processamento.',
                    'order' => 50,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-payrolls'],
                    'config_keys' => ['payroll_calendar'],
                    'evidence' => 'Calendário payroll visível e pronto para execução.',
                ],
                [
                    'key' => 'hr.run_payroll_test',
                    'checklist_key' => 'payroll_test',
                    'label' => 'Executar payroll de teste',
                    'description' => 'Processar uma folha de teste para validar cálculos, contribuições e permissões.',
                    'order' => 60,
                    'required' => true,
                    'module_refs' => ['Hrm'],
                    'permissions' => ['manage-payrolls', 'view-payrolls'],
                    'config_keys' => ['employee_masterdata', 'payroll_calendar', 'payroll_contributions'],
                    'evidence' => 'Payroll de teste concluído com INSS e IRPS configurados.',
                ],
            ],
        ],
        'treasury' => [
            'label' => 'Tesouraria',
            'priority' => 4,
            'technical_modules' => ['Account'],
            'required_permissions' => [
                'manage-bank-accounts',
                'manage-bank-transactions',
                'reconcile-bank-transactions',
                'manage-bank-transfers',
                'manage-customer-payments',
                'manage-vendor-payments',
            ],
            'required_config_keys' => [
                'bank_accounts',
                'cash_accounts',
                'payment_methods',
                'reconciliation_rules',
            ],
            'steps' => [
                [
                    'key' => 'treasury.create_bank_accounts',
                    'checklist_key' => 'bank_accounts',
                    'label' => 'Criar contas bancárias',
                    'description' => 'Registar as contas bancárias e de caixa usadas pela operação.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-bank-accounts'],
                    'config_keys' => ['bank_accounts', 'cash_accounts'],
                    'evidence' => 'Contas financeiras activas no sistema.',
                ],
                [
                    'key' => 'treasury.configure_payment_methods',
                    'checklist_key' => 'payment_methods',
                    'label' => 'Configurar meios de pagamento',
                    'description' => 'Definir meios de pagamento aceites e regras de uso.',
                    'order' => 20,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-customer-payments', 'manage-vendor-payments'],
                    'config_keys' => ['payment_methods'],
                    'evidence' => 'Meios de pagamento disponíveis para recebimentos e pagamentos.',
                ],
                [
                    'key' => 'treasury.configure_reconciliation_rules',
                    'checklist_key' => 'reconciliation_rules',
                    'label' => 'Configurar reconciliação',
                    'description' => 'Definir regras para reconciliação bancária e controle de movimentos.',
                    'order' => 30,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-bank-transactions', 'reconcile-bank-transactions'],
                    'config_keys' => ['reconciliation_rules'],
                    'evidence' => 'Regras de reconciliação activas.',
                ],
                [
                    'key' => 'treasury.record_initial_payments',
                    'checklist_key' => 'initial_payments',
                    'label' => 'Registar pagamentos iniciais',
                    'description' => 'Lançar um pagamento cliente e um pagamento fornecedor de teste.',
                    'order' => 40,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-customer-payments', 'manage-vendor-payments'],
                    'config_keys' => ['bank_accounts', 'payment_methods'],
                    'evidence' => 'Pagamentos de teste registados com sucesso.',
                ],
                [
                    'key' => 'treasury.perform_first_reconciliation',
                    'checklist_key' => 'first_reconciliation',
                    'label' => 'Executar primeira reconciliação',
                    'description' => 'Executar reconciliação inicial com saldo esperado e movimentação real.',
                    'order' => 50,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['reconcile-bank-transactions'],
                    'config_keys' => ['bank_accounts', 'reconciliation_rules'],
                    'evidence' => 'Reconciliação inicial concluída e conciliada.',
                ],
                [
                    'key' => 'treasury.validate_payment_flow',
                    'checklist_key' => 'payment_test',
                    'label' => 'Validar fluxo de pagamentos',
                    'description' => 'Validar o fluxo completo de pagamento para cliente e fornecedor.',
                    'order' => 60,
                    'required' => true,
                    'module_refs' => ['Account'],
                    'permissions' => ['manage-customer-payments', 'manage-vendor-payments'],
                    'config_keys' => ['bank_accounts', 'payment_methods', 'reconciliation_rules'],
                    'evidence' => 'Fluxo de pagamentos validado sem erros.',
                ],
            ],
        ],
        'inventory' => [
            'label' => 'Inventário',
            'priority' => 5,
            'technical_modules' => ['warehouses', 'ProductService'],
            'required_permissions' => [
                'manage-warehouses',
                'manage-stock',
                'manage-transfers',
            ],
            'required_config_keys' => [
                'warehouses',
                'initial_stock',
                'fifo_layers',
            ],
            'steps' => [
                [
                    'key' => 'inventory.create_warehouse',
                    'checklist_key' => 'create_warehouse',
                    'label' => 'Criar armazém',
                    'description' => 'Registar o primeiro armazém para suportar stock e POS.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['warehouses'],
                    'permissions' => ['manage-warehouses', 'create-warehouses'],
                    'config_keys' => ['warehouses'],
                    'evidence' => 'Armazém activo e pronto para stock.',
                ],
                [
                    'key' => 'inventory.load_initial_stock',
                    'checklist_key' => 'load_initial_stock',
                    'label' => 'Carregar stock inicial',
                    'description' => 'Criar o stock inicial com o custo base para gerar as layers FIFO.',
                    'order' => 20,
                    'required' => true,
                    'module_refs' => ['ProductService', 'warehouses'],
                    'permissions' => ['manage-stock', 'create-stock'],
                    'config_keys' => ['initial_stock'],
                    'evidence' => 'Stock inicial carregado no armazém.',
                ],
                [
                    'key' => 'inventory.verify_fifo_layers',
                    'checklist_key' => 'verify_fifo_layers',
                    'label' => 'Validar FIFO',
                    'description' => 'Confirmar que as layers FIFO existem e acompanham o stock activo.',
                    'order' => 30,
                    'required' => true,
                    'module_refs' => ['ProductService', 'warehouses'],
                    'permissions' => ['manage-stock'],
                    'config_keys' => ['fifo_layers'],
                    'evidence' => 'Layers FIFO disponíveis para o stock carregado.',
                ],
            ],
        ],
        'pos' => [
            'label' => 'POS',
            'priority' => 6,
            'technical_modules' => ['Pos', 'ProductService', 'warehouses'],
            'required_permissions' => [
                'manage-pos',
                'manage-pos-orders',
                'create-pos',
            ],
            'required_config_keys' => [
                'pos_registers',
            ],
            'steps' => [
                [
                    'key' => 'pos.run_test_sale',
                    'checklist_key' => 'run_pos_test',
                    'label' => 'Emitir venda POS de teste',
                    'description' => 'Abrir o POS e registar uma venda de validação com stock disponível.',
                    'order' => 10,
                    'required' => true,
                    'module_refs' => ['Pos', 'ProductService', 'warehouses'],
                    'permissions' => ['create-pos'],
                    'config_keys' => ['pos_registers'],
                    'evidence' => 'Venda POS de teste emitida com sucesso.',
                ],
            ],
        ],
    ],
];
