<?php

return [
    'catalog_version' => '2026-06-06',

    'features' => [
        [
            'key' => 'billing.invoice.create',
            'label' => 'Criar factura de venda',
            'domain' => 'billing',
            'modules' => ['Account', 'ProductService'],
            'permissions_any' => ['create-sales-invoices'],
            'config_keys' => ['fiscal_profile', 'accounting_period', 'document_series', 'tax_profile'],
            'route_prefixes' => ['sales-invoices'],
            'menu_groups' => ['Facturação'],
            'notes' => 'Criação de facturas de venda em rascunho.',
        ],
        [
            'key' => 'billing.invoice.post',
            'label' => 'Postar factura de venda',
            'domain' => 'billing',
            'modules' => ['Account', 'ProductService'],
            'permissions_any' => ['post-sales-invoices'],
            'config_keys' => ['fiscal_profile', 'accounting_period', 'document_series', 'tax_profile', 'chart_of_accounts'],
            'route_prefixes' => ['sales-invoices'],
            'menu_groups' => ['Facturação'],
            'notes' => 'Postagem contabilística e fiscal da factura.',
        ],
        [
            'key' => 'billing.customer.manage',
            'label' => 'Gerir clientes',
            'domain' => 'billing',
            'modules' => ['Account'],
            'permissions_any' => ['manage-customers'],
            'config_keys' => [],
            'route_prefixes' => ['account/customers'],
            'menu_groups' => ['Facturação'],
            'notes' => 'Cadastro e manutenção de clientes.',
        ],
        [
            'key' => 'billing.product.manage',
            'label' => 'Gerir artigos',
            'domain' => 'billing',
            'modules' => ['ProductService'],
            'permissions_any' => ['manage-product-service-item'],
            'config_keys' => [],
            'route_prefixes' => ['product-service/items'],
            'menu_groups' => ['Facturação', 'Inventário'],
            'notes' => 'Cadastro de artigos, serviços e preços.',
        ],
        [
            'key' => 'billing.return.manage',
            'label' => 'Gerir devoluções de venda',
            'domain' => 'billing',
            'modules' => ['Account'],
            'permissions_any' => ['manage-sales-return-invoices'],
            'config_keys' => ['fiscal_profile', 'document_series', 'tax_profile'],
            'route_prefixes' => ['sales-returns'],
            'menu_groups' => ['Facturação'],
            'notes' => 'Emissão e gestão de devoluções de venda.',
        ],
        [
            'key' => 'accounting.chart_of_accounts.manage',
            'label' => 'Gerir plano de contas',
            'domain' => 'accounting',
            'modules' => ['Account'],
            'permissions_any' => ['manage-chart-of-accounts'],
            'config_keys' => [],
            'route_prefixes' => ['account/chart-of-accounts'],
            'menu_groups' => ['Contabilidade'],
            'notes' => 'Plano de contas e contas contabilísticas.',
        ],
        [
            'key' => 'accounting.double_entry.post',
            'label' => 'Lançar em entrada dupla',
            'domain' => 'accounting',
            'modules' => ['Account', 'DoubleEntry'],
            'permissions_any' => ['manage-double-entry'],
            'config_keys' => ['accounting_period', 'chart_of_accounts', 'tax_profile'],
            'route_prefixes' => ['double-entry'],
            'menu_groups' => ['Contabilidade'],
            'notes' => 'Lançamentos contabilísticos e fecho operacional.',
        ],
        [
            'key' => 'accounting.trial_balance.view',
            'label' => 'Ver balancete',
            'domain' => 'accounting',
            'modules' => ['Account', 'DoubleEntry'],
            'permissions_any' => ['manage-trial-balance'],
            'config_keys' => ['accounting_period', 'chart_of_accounts'],
            'route_prefixes' => ['double-entry/trial-balance'],
            'menu_groups' => ['Contabilidade'],
            'notes' => 'Consulta e impressão do balancete.',
        ],
        [
            'key' => 'accounting.general_ledger.view',
            'label' => 'Ver razão geral',
            'domain' => 'accounting',
            'modules' => ['Account', 'DoubleEntry'],
            'permissions_any' => ['view-general-ledger'],
            'config_keys' => ['accounting_period', 'chart_of_accounts'],
            'route_prefixes' => ['double-entry/reports'],
            'menu_groups' => ['Contabilidade'],
            'notes' => 'Consulta do razão e relatórios de movimento.',
        ],
        [
            'key' => 'treasury.bank_accounts.manage',
            'label' => 'Gerir contas bancárias',
            'domain' => 'treasury',
            'modules' => ['Account'],
            'permissions_any' => ['manage-bank-accounts'],
            'config_keys' => [],
            'route_prefixes' => ['account/bank-accounts'],
            'menu_groups' => ['Tesouraria'],
            'notes' => 'Registo e manutenção de contas bancárias.',
        ],
        [
            'key' => 'treasury.bank_transactions.manage',
            'label' => 'Gerir movimentos bancários',
            'domain' => 'treasury',
            'modules' => ['Account'],
            'permissions_any' => ['manage-bank-transactions'],
            'config_keys' => [],
            'route_prefixes' => ['account/bank-transactions'],
            'menu_groups' => ['Tesouraria'],
            'notes' => 'Movimentos bancários, reconciliação e consultas.',
        ],
        [
            'key' => 'treasury.bank_transfers.manage',
            'label' => 'Gerir transferências bancárias',
            'domain' => 'treasury',
            'modules' => ['Account'],
            'permissions_any' => ['manage-bank-transfers'],
            'config_keys' => [],
            'route_prefixes' => ['account/bank-transfers'],
            'menu_groups' => ['Tesouraria'],
            'notes' => 'Transferências entre contas bancárias.',
        ],
        [
            'key' => 'treasury.customer_payments.manage',
            'label' => 'Gerir recebimentos',
            'domain' => 'treasury',
            'modules' => ['Account'],
            'permissions_any' => ['manage-customer-payments'],
            'config_keys' => ['chart_of_accounts'],
            'route_prefixes' => ['account/customer-payments'],
            'menu_groups' => ['Tesouraria'],
            'notes' => 'Recebimentos e baixa de faturas de clientes.',
        ],
        [
            'key' => 'treasury.vendor_payments.manage',
            'label' => 'Gerir pagamentos',
            'domain' => 'treasury',
            'modules' => ['Account'],
            'permissions_any' => ['manage-vendor-payments'],
            'config_keys' => ['chart_of_accounts'],
            'route_prefixes' => ['account/vendor-payments'],
            'menu_groups' => ['Tesouraria'],
            'notes' => 'Pagamentos a fornecedores e liquidação de obrigações.',
        ],
        [
            'key' => 'inventory.warehouse.manage',
            'label' => 'Gerir armazéns',
            'domain' => 'inventory',
            'modules' => ['warehouses'],
            'permissions_any' => ['manage-warehouses'],
            'config_keys' => [],
            'route_prefixes' => ['warehouses'],
            'menu_groups' => ['Inventário'],
            'notes' => 'Armazéns, localização e estrutura logística.',
        ],
        [
            'key' => 'inventory.stock.manage',
            'label' => 'Gerir stock',
            'domain' => 'inventory',
            'modules' => ['ProductService'],
            'permissions_any' => ['manage-stock'],
            'config_keys' => ['warehouses'],
            'route_prefixes' => ['product-service/stock'],
            'menu_groups' => ['Inventário'],
            'notes' => 'Movimentação e consulta de stock por artigo.',
        ],
        [
            'key' => 'inventory.transfer.manage',
            'label' => 'Gerir transferências de stock',
            'domain' => 'inventory',
            'modules' => ['ProductService'],
            'permissions_any' => ['manage-transfers'],
            'config_keys' => ['warehouses', 'initial_stock', 'fifo_layers'],
            'route_prefixes' => ['transfers'],
            'menu_groups' => ['Inventário'],
            'notes' => 'Transferências entre armazéns com impacto no FIFO.',
        ],
        [
            'key' => 'inventory.pos.manage',
            'label' => 'Gerir POS',
            'domain' => 'inventory',
            'modules' => ['Pos', 'ProductService', 'warehouses'],
            'permissions_any' => ['manage-pos', 'manage-pos-orders', 'create-pos'],
            'config_keys' => ['warehouses', 'initial_stock', 'fifo_layers'],
            'route_prefixes' => ['dashboard/pos', 'pos/orders', 'pos/create'],
            'menu_groups' => ['Inventário', 'POS'],
            'notes' => 'Ponto de venda, ordens e validação de stock em tempo real.',
        ],
        [
            'key' => 'hr.employee.manage',
            'label' => 'Gerir colaboradores',
            'domain' => 'hr',
            'modules' => ['Hrm'],
            'permissions_any' => ['manage-employees'],
            'config_keys' => [],
            'route_prefixes' => ['hrm/employees'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Cadastro, edição e consulta de colaboradores.',
        ],
        [
            'key' => 'hr.attendance.manage',
            'label' => 'Gerir assiduidade',
            'domain' => 'hr',
            'modules' => ['Hrm'],
            'permissions_any' => ['manage-attendances'],
            'config_keys' => [],
            'route_prefixes' => ['hrm/attendances'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Registo de entradas, saídas e presença.',
        ],
        [
            'key' => 'hr.leave.manage',
            'label' => 'Gerir ausências',
            'domain' => 'hr',
            'modules' => ['Hrm'],
            'permissions_any' => ['manage-leave-applications'],
            'config_keys' => [],
            'route_prefixes' => ['hrm/leave-applications'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Pedidos de férias, faltas e aprovações.',
        ],
        [
            'key' => 'hr.payroll.run',
            'label' => 'Executar folha salarial',
            'domain' => 'hr',
            'modules' => ['Hrm'],
            'permissions_any' => ['manage-payrolls'],
            'config_keys' => ['payroll_calendar', 'payroll_contributions'],
            'route_prefixes' => ['hrm/payrolls'],
            'menu_groups' => ['Recursos Humanos'],
            'notes' => 'Processamento e validação de folha salarial com calendário e contribuições configuradas.',
        ],
    ],
];
